// Code generated by "stringer -type=connState"; DO NOT EDIT.

package psst

import "strconv"

const _connState_name = "closedlistensynSentsynReceivedopencloseWait"

var _connState_index = [...]uint8{0, 6, 12, 19, 30, 34, 43}

func (i connState) String() string {
	if i < 0 || i >= connState(len(_connState_index)-1) {
		return "connState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _connState_name[_connState_index[i]:_connState_index[i+1]]
}
